version: 0.2

# Pre-requisites
# - Create CodeBuild project
#   - Provide minimal github credentials to access public repo

phases:
  pre_build:
    on-failure: ABORT
    commands:
    - cp settings.xml ~/.m2/
    - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain cdlib-uc3-mrt --domain-owner $AWS_ACCOUNT_ID --region $AWS_REGION --query authorizationToken --output text`
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${ECR_REGISTRY}

    - COMMIT=`git rev-parse --short HEAD`
    - BRANCH=`git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || echo ''`
    - TAG=`git describe --tags --exact-match 2> /dev/null || echo ''`
    - BRANCHTAG=`git describe --tags --exact-match 2> /dev/null || git symbolic-ref -q --short HEAD || git name-rev $(git rev-parse --short HEAD) | cut -d' ' -f2 || git rev-parse --short HEAD`
    - echo "Branchtag ${BRANCHTAG}; COMMITDATE=${COMMITDATE}; REPONAME=${REPONAME}; BRANCHNAME=${BRANCHNAME}"

  build:
    on-failure: ABORT
    commands:
    # - mvn -ntp clean install -Ddocker.skip -DskipITs -Dmaven.test.skip=true
    - mvn -ntp clean install
    - mvn deploy:deploy-file -Durl=${CODEARTIFACT_URL} -DrepositoryId=cdlib-uc3-mrt-uc3-mrt-java -Dfile=$(ls cloud-conf/target/mrt-cloudconf-*.jar)
    - mvn deploy:deploy-file -Durl=${CODEARTIFACT_URL} -DrepositoryId=cdlib-uc3-mrt-uc3-mrt-java -Dfile=$(ls openstack-src/target/mrt-openstackpub-*.jar)
    - mvn deploy:deploy-file -Durl=${CODEARTIFACT_URL} -DrepositoryId=cdlib-uc3-mrt-uc3-mrt-java -Dfile=$(ls s3-src/target/mrt-s3srcpub-*.jar)
    - |
      for pkg in mrt-cloudconf mrt-openstackpub mrt-s3srcpub
      do
        for ver in `aws codeartifact list-package-versions \
          --domain=cdlib-uc3-mrt --repository=uc3-mrt-java \
          --format=maven --namespace=org.cdlib.mrt \
          --package=$pkg --status=Unlisted \
          --output=text | grep Unlisted | cut -f4`
        do
          aws codeartifact delete-package-versions \
            --domain=cdlib-uc3-mrt --repository=uc3-mrt-java \
            --format=maven --namespace=org.cdlib.mrt \
            --package=$pkg --versions=$ver --no-cli-pager
        done
      done
    - mvn -ntp javadoc:javadoc
    - rm -rf api/mrt-cloud
    - mkdir -p api/mrt-cloud/java
    - cp -r openstack-src/target/site/apidocs/* api/mrt-cloud/java
    - cp -r s3-src/target/site/apidocs/* api/mrt-cloud/java
    - echo aws s3 cp --recursive api s3://${S3CFBUCKET}/api 
    - aws s3 cp --recursive api s3://${S3CFBUCKET}/api
    - aws cloudfront create-invalidation --distribution-id ${CFDISTRIBUTIONID} --paths /* --region us-east-1
