---
node-table: "{!ENV: NODE_TABLE}"
aws-s3-version: "{!SSM: cloud/nodes/aws-s3-version !DEFAULT: 1}"
services: &services
  aws-near: &aws-near
    type: aws-near
    service-properties:
      serviceType: aws
      accessMode: near-line
      region: us-west-2
      
  aws-near-east: &aws-near-east
    type: aws-near
    service-properties:
      serviceType: aws
      accessMode: near-line
      region: us-east-1

  aws-std: &aws-std
    type: aws-std
    service-properties:
      serviceType: aws
      accessMode: on-line
      storageClass: Standard
      region: us-west-2

  ch-unm-prd: &ch-unm-prd
    type: ch-unm-prd
    service-properties:
      serviceType: cloudhost
      base: http://oneshare.unm.edu:8080/cloudhost

  minio-sdsc-new: &minio-sdsc-new
    type: minio-sdsc
    service-properties:
      serviceType: minio
      endPoint: https://cdl.s3.sdsc.edu:443
      accessKey: "{!SSM: cloud/nodes/sdsc-accessKey !DEFAULT: SSMFAIL}"
      secretKey: "{!SSM: cloud/nodes/sdsc-secretKey !DEFAULT: SSMFAIL}"

  minio-docker: &minio-docker
    type: minio-docker
    service-properties:
      serviceType: minio
      # Note, we use ec2_host:8088 on our ec2 docker test machine
      endPoint: "http://{!ENV: MRT_MINIO_HOST !DEFAULT: my-minio-localhost-alias}:{!ENV: MRT_MINIO_PORT !DEFAULT: 8088}"
      accessKey: minioadmin
      secretKey: minioadmin
      
  sdsc-s3: &sdsc-s3
    type: sdsc-s3
    service-properties:
      serviceType: sdsc-s3
      endPoint: https://uss-s3.sdsc.edu:443
      #accessKey: "{!SSM: cloud/nodes/sdsc-s3-accessKey !DEFAULT: 000000050012f3304cf6}"
      #secretKey: "{!SSM: cloud/nodes/sdsc-s3-secretKey !DEFAULT: xdWhD/VoOzLUq4Nn6z3RQ99cEok27PiVMDYPJnog}"
      accessKey: "{!SSM: cloud/nodes/sdsc-s3-accessKey !DEFAULT: SSMFAIL}"
      secretKey: "{!SSM: cloud/nodes/sdsc-s3-secretKey !DEFAULT: SSMFAIL}"

  wasabi-east: &wasabi-east
    type: wasabi-east
    service-properties:
      serviceType: wasabi
      endPoint: https://s3.us-east-2.wasabisys.com:443
      accessKey: "{!SSM: cloud/nodes/wasabi-accessKey !DEFAULT: SSMFAIL}"
      secretKey: "{!SSM: cloud/nodes/wasabi-secretKey !DEFAULT: SSMFAIL}"
      regionName: us-east-2

nodes-tables:
  nodes-prod:
      - # AWS Standard
        identifier: 5001
        <<: *aws-std
        bucket: uc3-s3mrt5001-prd
        desc: "AWS standard prod"

      - # AWS Glacier
        identifier: 6001
        <<: *aws-near
        bucket: uc3-s3mrt6001-prd
        desc: "AWS glacier prod"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-prd
        desc: "###ArchiveNode"

      - # SDSC backup
        identifier: 7501
        <<: *sdsc-s3
        bucket: cdl-sdsc-backup-prod
        desc: "sdsc s3 backup prod"

      - # SDSC Minio, Mar 2020
        identifier: 9501
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.prod
        desc: "sdsc minio prod"

      - # Wasabi
        identifier: 2001
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.prod
        desc: "wasabi s3 prod"

  nodes-stage:
      - # AWS Standard
        identifier: 5001
        <<: *aws-std
        bucket: uc3-s3mrt5001-stg
        desc: "AWS standard stage"

      - # AWS Glacier
        identifier: 6001
        <<: *aws-near
        bucket: uc3-s3mrt6001-stg
        desc: "AWS glacier stage"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-stg
        desc: "###ArchiveNode"

      - # SDSC backup
        identifier: 7502
        <<: *sdsc-s3
        bucket: cdl-sdsc-backup-stg
        desc: "sdsc backup stage"

      - # SDSC Minio
        identifier: 9502
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.stage
        desc: "sdsc minio stage"

      - # Wasabi
        identifier: 2002
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.stage
        desc: "wasabi s3"

  nodes-dev:
      - # AWS Standard
        identifier: 5003
        <<: *aws-std
        bucket: uc3-s3mrt5001-dev
        desc: "AWS standard stage"

      - # AWS Glacier
        identifier: 6003
        <<: *aws-near
        bucket: uc3-s3mrt6001-dev
        desc: "AWS glacier stage"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-dev
        desc: "###ArchiveNode"

      - # SDSC Minio
        identifier: 9503
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.dev
        desc: "sdsc minio"

      - # Wasabi
        identifier: 2003
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.dev
        desc: "wasabi s3"

  nodes-pairtree-docker:
      - # Minio Docker
        identifier: 7777
        <<: *minio-docker
        bucket: my-bucket
        desc: "docker minio 7777"
      - # Minio Docker Replic
        identifier: 8888
        <<: *minio-docker
        bucket: my-bucket-repl
        desc: "docker minio 8888"

  nodes-ecs-docker:
      - # Minio Docker
        identifier: 7777
        <<: *aws-std
        bucket: uc3-mrt-ecs-dev-my-bucket
        desc: "ecs dev 7777"
      - # Minio Docker Replic
        identifier: 8888
        <<: *aws-std
        bucket: uc3-mrt-ecs-dev-my-bucket-repl
        desc: "ecs dev 8888"

  nodes-prod-post-dryad:
      - # AWS Standard
        identifier: 5001
        <<: *aws-std
        bucket: uc3-s3mrt5001-prd
        desc: "AWS standard prod"

      - # AWS Glacier
        identifier: 6001
        <<: *aws-near
        bucket: uc3-s3mrt6001-prd
        desc: "AWS glacier prod"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-prd
        desc: "###ArchiveNode"

      - # SDSC backup
        identifier: 7501
        <<: *sdsc-s3
        bucket: cdl-sdsc-backup-prod
        desc: "sdsc s3 backup prod"

      - # SDSC Minio, Mar 2020
        identifier: 9501
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.prod
        desc: "sdsc minio prod"

      - # Wasabi
        identifier: 2001
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.prod
        desc: "wasabi s3 prod"

  nodes-stage-post-dryad:
      - # AWS Standard
        identifier: 5001
        <<: *aws-std
        bucket: uc3-s3mrt5001-stg
        desc: "AWS standard stage"

      - # AWS Glacier
        identifier: 6001
        <<: *aws-near
        bucket: uc3-s3mrt6001-stg
        desc: "AWS glacier stage"

      - # Merritt Cloudhost - on AWS
        identifier: 7001
        <<: *aws-std
        bucket: uc3-s3mrt1001-stg
        desc: "###ArchiveNode"

      - # SDSC backup
        identifier: 7502
        <<: *sdsc-s3
        bucket: cdl-sdsc-backup-stg
        desc: "sdsc backup stage"

      - # SDSC Minio
        identifier: 9502
        <<: *minio-sdsc-new
        bucket: cdl.sdsc.stage
        desc: "sdsc minio stage"

      - # Wasabi
        identifier: 2002
        <<: *wasabi-east
        bucket: uc3-wasabi-useast-2.stage
        desc: "wasabi s3"